services:
  - type: web
    name: event-review-platform
    runtime: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn 'app:create_app()' -w 4 -b 0.0.0.0:$PORT --log-level info"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: run.py
      - key: FLASK_DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
